"""
Django settings for hearth_shop project.
Generated by 'django-admin startproject' using Django 5.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import logging
from pathlib import Path
from urllib.parse import urlparse, parse_qsl

from decouple import config
from dotenv import load_dotenv
import dj_database_url
import cloudinary

load_dotenv()

# ---------------------------------------------------------
# BASE CONFIG
# ---------------------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = config('DEBUG', default=False, cast=bool)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = config('SECRET_KEY')

# ---------------------------------------------------------
# LOGGING
# ---------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}

# -------------------------
# INSTALLED APPS
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    # 'django_extensions',
    'cloudinary',
    'cloudinary_storage',
]

# -------------------------
# AUTHENTICATION REDIRECTS
# -------------------------
LOGIN_REDIRECT_URL = 'illustration_gallery'
LOGOUT_REDIRECT_URL = 'login'

# ---------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hearth_shop.urls'

# ---------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'hearth_shop' / 'templates',
                 BASE_DIR / 'shop' / 'templates',
                 ],
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Injects cart item count
                'shop.context_processors.cart_count',
                # Injects cart total price
                'shop.context_processors.cart_total',
                # Injects user info if logged in
                'shop.context_processors.user_profile',
                # Injects site-wide settings like name and currency
                'shop.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'hearth_shop.wsgi.application'

# -------------------------
# ALLOWED HOSTS
# -------------------------
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = config(
        'ALLOWED_HOSTS',
        default='hearth-design-044ecd91e469.herokuapp.com'
    ).split(',')
    # Secure cookies for production (Heroku uses HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# -------------------------
# DATABASES
# -------------------------
if DEBUG:
    # Local development — parse Neon URL from .env
    tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.replace('/', ''),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': tmpPostgres.port or 5432,
            'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
        }
    }

else:
    # Production on Heroku — Heroku injects DATABASE_URL automatically
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
# -----------------------------
# Supabase S3 config
# -----------------------------
# AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_ACCESS_KEY')
# AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_SECRET_KEY')
# AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_ENDPOINT')
# AWS_S3_REGION_NAME = "us-east-1"
# AWS_S3_SIGNATURE_VERSION = "s3v4"

# -----------------------------
# MEDIA STORAGE CONFIGURATION
# -----------------------------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
)

# ---------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'
PREFIX_DEFAULT_LANGUAGE = True
LANGUAGE_COOKIE_PATH = '/'

TIME_ZONE = 'UTC'
USE_TZ = True
# Enable i18n
USE_I18N = True
LANGUAGES = [
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('fr', 'Français'),
    ('es', 'Español'),
    ('it', 'Italiano'),
    ('pt', 'Português'),
    ('zh-hans', '简体中文'),
    ('ja', '日本語'),
]
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SAMESITE = 'Lax'
LANGUAGE_COOKIE_USE_SESSION = False

# ---------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'

# Local development: static file locations
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'hearth_shop' / 'static',
    ]
# Production: where collectstatic will put everything
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise storage backend for Heroku
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
# ---------------------------------------------------------
# MEDIA
# ---------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media', ) 

# LOCALE_PATHS = [os.path.join(BASE_DIR, 'shop', 'locale')]
# LOCALE_PATHS = [os.path.join(BASE_DIR, 'shop.locale')]

# ---------------------------------------------------------
# EMAIL
# ---------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')