  BBBB BBBB

XXXX XXXXXX XXX
XXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'HOME') XXXXXXXXX
      XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'ILLUSTRATIONS') XXXXXXXXX
      XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'PHOTOGRAPHY') XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'THEME') XXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
          XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBB
              XXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBXXXXXXXXX
            BBBBBB
          XXXXXXXXX
        XXXXXXX
      XXXXX
    XXXXX

    XXXX XXXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBB
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'Upload') XXXXXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXX
            X  gettext(u'Cart')  X  X
          XXXX
        XXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'My Orders') XXXXXXXXX
        XXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Logout') XXXXXXXXX
          XXXXXXX
        XXXXX
      BBBB
        XXXXXX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXX gettext(u'Login') XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXX gettext(u'Sign Up') XXXXXXXXX
      BBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX  
        XXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Switch Language') XXXXXXXXX
        
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'English') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'Deutsch') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'Français') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'Español') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'Italiano') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'Português') XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXX gettext(u'简体中文') XXXXXXXXX
              XXXXXXX XXXXXXXXXXX gettext(u'日本語') XXXXXXXXX
            XXXXXXXXX
          XXXXXXX
        XXXXX
    XXXXX
  XXXXXX
XXXXXX

 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

