XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBBBB
    BBBB BBBB
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'Hearth Shop') BBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXX XXXXX XXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

    XXXX XXXXXXXX XXXXXXXX XXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBXX
    XXXX XXX XXXXXXXX XXX
    XXXXX XXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX gettext(u'SHOP') XXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

    XXXXXXXXX
XXXXXX
  BBBBB BBBBBBBBBBBBBBB
XXXXXXX

XXXX  XXXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
  
  XXXX XXXXX XXXXXXX XXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX  XXXXX XXXXXXX XXX
    XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXXXXX

    XXXX XXX XX XXXX XXXX XXXXX XXX XXXXXXXXX XXXXXX XXX
    BB BBB BBBBBBBBBBBBB
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX gettext(u'Quantity:') XXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Add to Cart') XXXXXXXXX
      XXXXXXX
    BBBBB

    XXXX XXXXXXXXXX XXX XXXXX XXXXXXXX XXXXX XX XXXXXX XXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

  XXXXXX XXXX XXX XX XXXXXXXXXXXXXX XXX

XXXXXX XXXX  XXX XX XXXXXXXXXXXX XXX

XXXX XXXXXX XXX
XXXXXXXX
  XXXXXXXXX XXXX XXXXXX XXXXXXXX
  XX XXXXXXBBB BBBBBBBBBXX gettext(u'Contact Us') XXXX
XXXXXXXXX
XXXXXXX
XXXXXXX
