# Generated by Django 5.2.6 on 2025-10-04 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_print_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
    ]
