# Generated by Django 5.2.6 on 2025-11-28 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='photography',
            options={'verbose_name': 'Photography', 'verbose_name_plural': 'Photographies'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('product', 'Product'), ('blog', 'Blog'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='ip_hash',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='user_agent',
            field=models.TextField(default='unknown'),
        ),
    ]
