# Generated by Django 5.2.6 on 2025-11-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='illustrations/')),
                ('in_stock', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='shop.print')),
                ('themes', models.ManyToManyField(blank=True, to='shop.theme')),
            ],
            options={
                'verbose_name': 'Illustration',
                'verbose_name_plural': 'Illustrations',
            },
        ),
    ]
