# Generated by Django 5.2.6 on 2025-11-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='print',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='prints',
            field=models.ManyToManyField(through='shop.CartItem', to='shop.print'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='print',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.print'),
        ),
        migrations.AddField(
            model_name='print',
            name='format',
            field=models.CharField(blank=True, choices=[('metal', 'Metal Print'), ('wood', 'Wood Print'), ('paper', 'Paper Print')], max_length=50),
        ),
        migrations.AddField(
            model_name='print',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='print',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='print',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='print',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('print', 'Print'), ('blog', 'Blog'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='photography',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='print',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddIndex(
            model_name='print',
            index=models.Index(fields=['sku'], name='shop_print_sku_f81407_idx'),
        ),
        migrations.AddIndex(
            model_name='print',
            index=models.Index(fields=['price'], name='shop_print_price_4928d5_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='print',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.print'),
        ),
        migrations.AddField(
            model_name='order',
            name='prints',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.print'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
