# Generated by Django 5.2.6 on 2025-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_remove_product_print_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
