# Generated by Django 5.2.6 on 2026-03-11 03:41

import shop.storage_backups
import shop.storage_cloudinary
import shop.storage_supabase
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='backup',
            field=models.FileField(blank=True, null=True, storage=shop.storage_backups.SupabaseBackupsStorage(), upload_to='backups/'),
        ),
        migrations.AddField(
            model_name='print',
            name='manual',
            field=models.FileField(blank=True, null=True, storage=shop.storage_supabase.SupabaseDocumentsStorage(), upload_to='manuals/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.storage_cloudinary.CloudinaryMediaStorage(), upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.storage_cloudinary.CloudinaryMediaStorage(), upload_to='illustrations/'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.storage_cloudinary.CloudinaryMediaStorage(), upload_to='photographies/'),
        ),
        migrations.AlterField(
            model_name='print',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.storage_cloudinary.CloudinaryMediaStorage(), upload_to='prints/%Y/%m%d'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=shop.storage_cloudinary.CloudinaryMediaStorage(), upload_to='theme_icons/'),
        ),
    ]
