# Generated by Django 5.2.6 on 2025-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
